Update Footer
tandil-dev/frontend-infraction pull request #69
Opened 2020-07-10 15:37 UTC by fedelmar

Add tabs

2020-07-10 19:59 UTC, MatiasOS requested changes
Además de lo anterior, también hace unos saltos que afectan bastante la visual.

2020-07-10 19:59 UTC, MatiasOS commented on src/components/InfractionDetails/index.js
> +  // eslint-disable-next-line
La idea de los warnings es arreglarlos, no ignorarlos :smile:

2020-07-10 19:59 UTC, MatiasOS commented on src/components/Footer/index.js
> +              aria-label="icon tabs example"
Remover este aria label porfa!

2020-07-10 19:59 UTC, MatiasOS commented on src/components/Footer/index.js
> +                <Tab icon={<AddAPhoto />} label="Reportar" component={Link} to="/report" />
Con el botón pasa algo medio raro.  No lo pinta correctamente. Queda pintado el botón anterior. 
![report](https://user-images.githubusercontent.com/5481398/87192426-d0c66000-c2cc-11ea-950a-efff45d7fcb7.png)

2020-07-10 19:59 UTC, MatiasOS commented on src/components/Footer/index.js
> +                <Tab icon={<AddAPhoto />} label="Reportar" component={Link} to="/report" />
Sospecho debe ser porque está envuelto en ` <MetamaskGateway> ... </MetamaskGateway>`.

2020-07-10 20:03 UTC, fedelmar commented on src/components/InfractionDetails/index.js
> +  // eslint-disable-next-line
jaja tome la salida facil

2020-07-10 20:07 UTC, fedelmar commented on src/components/Footer/index.js
> +                <Tab icon={<AddAPhoto />} label="Reportar" component={Link} to="/report" />
si, debe ser por eso porque antes de que lo agregue funcionaba bien.

2020-07-11 18:27 UTC, MatiasOS submitted a review, later dismissed
:raised_hands: :raised_hands:  :raised_hands:

2020-07-13 17:09 UTC, SabrinaDominguez commented
- [ ] Habría que cambiar las palabras del menú inferior por minúsculas. "Perfil" "Más" y "Reportar". 

- [ ] Me parece que el menú es muy alto. ¿Se puede achicar en tamaño, en ancho? En la compu lo veo grande. Y en el celu no puedo ver el cambio aún, no me lo muestra para verificar bien el tamaño. 
Justificación: roba mucho espacio en la pantalla para mostrar bien la información de todos los datos que el usuario tiene que cargar para hacer la infracción.

- [ ]   La palabra "Más" tiene que quedar alineada a la misma altura que el resto de las otras dos palabras "Perfil" y "Reportar".

2020-07-13 17:12 UTC, SabrinaDominguez requested changes
Alinear el texto a partir de la **"línea base"** **(baseline)**

![Menu inferior](https://user-images.githubusercontent.com/65744576/87332995-d9a87300-c512-11ea-8830-62e2ee120ff5.jpg)

Fuente: Instagram, es una pagina educativa **@uxcel.app**

![Screenshot_2020-07-13-16-07-15](https://user-images.githubusercontent.com/65744576/87343875-e97c8300-c523-11ea-896d-5ccbac2a85a9.png)

![Screenshot_2020-07-13-16-00-38](https://user-images.githubusercontent.com/65744576/87343974-07e27e80-c524-11ea-9aa8-1379850379a0.png)

2020-07-16 23:25 UTC, MatiasOS submitted a review, later dismissed

2020-07-20 17:57 UTC, SabrinaDominguez commented
Bárbaro chicos, quedo bien alineado y las palabras puestas. Lo único, pude ver como quedaba en el celu y me sigue pareciendo muy alto el tamaño del menú (flecha roja en la foto). ¿Hay posibilidad de achicarlo un poco?

Justificación: Noten el ancho que tiene el menú de navegación del celular. Se puede ver, que es menos ancho que el que nosotros estamos proponiendo.

![Altura menu principal](https://user-images.githubusercontent.com/65744576/87969621-e25ff280-ca98-11ea-81ce-d64ffbbe4ab7.jpg)

2020-07-27 14:25 UTC, MatiasOS submitted a review, later dismissed

2020-07-27 22:18 UTC, SabrinaDominguez approved these changes
Genial chicos!!!!! :D

2020-07-27 22:19 UTC, merged

2020-07-30 07:58 UTC, fMercury commented
Hola! :)
En los tres box  hay una diferencia decremental en el borde inferior. No se si se alcanza a apreciar en la imagen.
Tal vez es un efecto buscado, pero  cuando se cambia el porcentaje del navegador se alborotan los valores de los bordes y bueno cambia . 
 
![image](https://user-images.githubusercontent.com/5529152/88896831-b0921d00-d24a-11ea-9ebe-d0a25d68a681.png)