button loggin
tandil-dev/frontend-infraction pull request #70
Opened 2020-07-11 19:00 UTC by Ezequiel-A

actualizacion del boton login

2020-07-11 20:18 UTC, MatiasOS requested changes
También, en el archivo `Login/Form.js` en la lína 34, que te quede como `login: viewlogin,`

2020-07-11 20:18 UTC, MatiasOS commented on src/redux/actions/viewloginaction.js
> +export const type = 'viewlogionaction';
Porfa, cambiale acá por `export const viewLoginType = 'VIEW-LOGIN';`

2020-07-11 20:18 UTC, MatiasOS commented on src/pages/Login/Form.js
> +import viewlogin from '../../redux/actions/viewloginaction';
Acá cambiá el nombre al archivo por `viewLoginAction`

2020-07-11 20:18 UTC, MatiasOS commented on src/pages/Login/Form.js
> +import viewlogin from '../../redux/actions/viewloginaction';
y nombrá también el archivo XD

2020-07-13 16:32 UTC, SabrinaDominguez commented
No me doy cuenta de cual es el cambio chicos....

2020-07-16 23:20 UTC, MatiasOS approved these changes

2020-07-16 23:20 UTC, MatiasOS commented on src/redux/actions/viewLoginAction.js
> +  type,
Este type debería ser `type: viewLoginType`.

2020-07-16 23:20 UTC, MatiasOS commented on src/redux/actions/viewLoginAction.js
> +    email,
`email` y `password` no son necesarios. Esto debería ser
```javascript
payload: {},
```

2020-07-16 23:21 UTC, merged